version: '3'

services:
  news:
    build:
      context: prototype-gonews/cmd/server
    ports:
      - "8081:8081"

  comments:
    build:
      context: comments/cmd/server
    ports:
      - "8082:8082"

  censor:
    build:
      context: censorship
    ports:
      - "8083:8083"

  apigateway:
    build:
      context: api
    ports:
      - "8080:8080"
    depends_on:
      - news
      - comments
      - censor
